name: Metrics

on:
  schedule:
    - cron: "0 17 * * *"  # Mỗi ngày chạy 0h theo giờ Việt Nam (UTC+7)
  workflow_dispatch:        # Cho phép chạy thủ công từ giao diện GitHub

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: truongbi01
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh
          debug: true
